title: Dr. Bikash Gyawali
logo: /assets/img/headshot_circle.png
description: AWS certified Data Scientist working on NLP, Machine Learning, Document Processing and Big data analysis.
email: bikash.gyawali@outlook.com
show_downloads: false
theme: jekyll-theme-minimal
